version: '3.8'

services:
  rps_nginx:
    image: nginx:alpine
    container_name: rps_nginx
    ports:
      - "8084:80"
      - "8445:443"
    volumes:
      - /home/opc/projetos/rps:/usr/share/nginx/html
      - ./nginx/rps.conf:/etc/nginx/conf.d/default.conf
    networks:
      - global_net
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=rps"
      - "com.docker.compose.service=nginx"

  rps_backend:
    build:
      context: /home/opc/projetos/rps
      dockerfile: Dockerfile
    container_name: rps_backend
    ports:
      - "8085:3000"
    volumes:
      - /home/opc/projetos/rps:/app
      - /home/opc/projetos/rps/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - global_net
    restart: unless-stopped
    depends_on:
      - rps_nginx
    labels:
      - "com.docker.compose.project=rps"
      - "com.docker.compose.service=backend"

networks:
  global_net:
    external: true

volumes:
  rps_data:
    driver: local
