version: '3.8'

services:
  rps_nginx:
    image: nginx:alpine
    container_name: rps_nginx
    ports:
      - "5018:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/rps.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - rps_network
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=rps"
      - "com.docker.compose.service=nginx"

  rps_backend:
    build: .
    container_name: rps_backend
    ports:
      - "5019:3000"
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - rps_network
    restart: unless-stopped
    depends_on:
      - rps_nginx
    labels:
      - "com.docker.compose.project=rps"
      - "com.docker.compose.service=backend"

networks:
  rps_network:
    driver: bridge

volumes:
  rps_data:
    driver: local
